import lodash from 'lodash';
import dayjs from 'dayjs';

const getParams = (method) => {
    if (method === 'GET') return 'params = {}';
    return 'params = {}, body = {}';
}

const evaluatePayloadKey = (method) => {
    if (method === 'GET') return '';
    return 'body:  JSON.stringify(body)';
}
function getJavaScript(url, method, payload, responseType, intent = {}) {
  if (!intent.route_name) return;
  const action = intent?.route_name.split('/').filter(item => !!item).map(item => lodash.upperFirst(item).replaceAll('-', '_')).join('');
  const fullAction = [method.toLowerCase(), action].join('');
    if (responseType) return null;
    let body = "";
    if (payload) {
      body = `body:  ${JSON.stringify(payload, null, 8)}`;
    }
    let tmpl = `/*
   *
   * Summary ${intent.summary}
   * API ${intent?.route_name}
   * Method ${method}
   * 
   */

  async ${fullAction} (${getParams(method)}) {
    const qs = new URLSearchParams({ ...params, api_token: this.api_token });
    const url = this.endpoint + '{{url}}?' + qs.toString();
    const result = await fetch(url, {
      method: '{{method}}',
      headers: { 
        'Content-Type': 'application/json' 
      },
      ${evaluatePayloadKey(method)}
    });
    const resp = await result.json();
    const data = await resp.json();
    return data;
  };
`;

    const final = lodash.template(tmpl)({
        body, method, url
    });
    return final;
}

export default function sdk (list = [], provider, endpoint, language = 'JavaScript') {
const codeList = [];
list.forEach((item) => {
    const gen = getJavaScript(`${item.route_name}`, item.method, {}, null, item);
    codeList.push(gen);
});

const tmpl = `
/* ${lodash.upperFirst(provider)} LowCodeAPI ${language} client library */
/* Build Version: ${dayjs().format('YYYY-MM-DD HH:mm:ss')}*/
/*
* ${lodash.upperFirst(provider)} methods are generated by LowCodeAPI.
* LowCodeAPI simplifies the api access and provides wrapper on top of the official ${lodash.upperFirst(provider)} APIs.
* All the methods call routed via https://api.lowcodeapi.com.
* The ${lodash.upperFirst(provider)} credentials are configured at https://lowcodeapi.com/${provider}?setup=1
* The request activity can be viewed at https://lowcodeapi.com/${provider}
*/

class ${lodash.upperFirst(provider)} {
    constructor(endpoint, api_token, endpoint = '${endpoint}') {
        this.__created_at = '${dayjs().format('YYYY-MM-DD HH:mm:ss')}';
        this.connector = '${provider}';
        this.endpoint = endpoint;
        this.api_token = api_token;
    }
        ${codeList.join('\n')}
}
`
return tmpl;
}